use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuildDoctorStatus {
    pub version: String,
    pub purpose: String,
    pub cargo_feature: String,
    pub default_build_command: String,
    pub feature_build_command: String,
    pub frontend_commands: Vec<String>,
    pub ci_commands: Vec<String>,
    pub expected_outputs: Vec<String>,
    pub blocked_in_current_environment: Vec<String>,
    pub warning: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalValidationPlanInput {
    pub rust_installed: bool,
    pub default_cargo_check_passed: bool,
    pub feature_cargo_check_passed: bool,
    pub frontend_build_passed: bool,
    pub clean_clone_tested: bool,
    pub generated_signet_funding_address: bool,
    pub mainnet_lightning_requested: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalValidationPlan {
    pub ready_for_next_ldk_step: bool,
    pub safe_for_real_mainnet: bool,
    pub passed: Vec<String>,
    pub blockers: Vec<String>,
    pub local_commands: Vec<String>,
    pub next_code_targets: Vec<String>,
    pub warning: String,
}

pub fn status() -> BuildDoctorStatus {
    BuildDoctorStatus {
        version: "v0.15".to_string(),
        purpose: "Local compile-validation checkpoint for CarlosK Wallet before deeper embedded Lightning work.".to_string(),
        cargo_feature: "ldk-node-signet-runtime".to_string(),
        default_build_command: "cd src-tauri && cargo check".to_string(),
        feature_build_command: "cd src-tauri && cargo check --features ldk-node-signet-runtime".to_string(),
        frontend_commands: vec![
            "npm install --ignore-scripts --no-audit --no-fund".to_string(),
            "npx tsc --noEmit".to_string(),
            "npx vite build".to_string(),
        ],
        ci_commands: vec![
            "npm run check:frontend".to_string(),
            "npm run check:tauri".to_string(),
            "npm run check:tauri:ldk".to_string(),
        ],
        expected_outputs: vec![
            "Default backend cargo check passes without enabling ldk-node".to_string(),
            "Feature-gated ldk-node build either passes or produces a concrete API mismatch to fix".to_string(),
            "Frontend TypeScript and Vite production build pass".to_string(),
            "No mainnet embedded Lightning path can be enabled from the UI".to_string(),
        ],
        blocked_in_current_environment: vec![
            "This ChatGPT sandbox has Node/npm but does not have rustc/cargo installed".to_string(),
            "Real ldk-node API compile validation must be run on the developer machine or GitHub Actions".to_string(),
        ],
        warning: "v0.15 does not claim a viable all-in-one Lightning wallet. It adds the build-doctor path that tells us exactly what must pass before v0.20 can wire a real signet funding-address command.".to_string(),
    }
}

pub fn build_plan(input: LocalValidationPlanInput) -> LocalValidationPlan {
    let mut passed = Vec::new();
    let mut blockers = Vec::new();

    if input.rust_installed {
        passed.push("Rust toolchain is installed locally".to_string());
    } else {
        blockers.push("Install Rust with rustup before backend validation".to_string());
    }

    if input.frontend_build_passed {
        passed.push("Frontend typecheck and production build passed".to_string());
    } else {
        blockers.push("Run `npm run check:frontend` and fix TypeScript/Vite errors".to_string());
    }

    if input.default_cargo_check_passed {
        passed.push("Default Rust/Tauri backend cargo check passed".to_string());
    } else {
        blockers.push("Run `npm run check:tauri` and fix default backend errors".to_string());
    }

    if input.feature_cargo_check_passed {
        passed.push("Feature-gated ldk-node cargo check passed".to_string());
    } else {
        blockers.push("Run `npm run check:tauri:ldk`; capture the first ldk-node API mismatch if it fails".to_string());
    }

    if input.clean_clone_tested {
        passed.push("Clean clone validation completed".to_string());
    } else {
        blockers.push("Test from a clean unzip/clone so hidden local files do not mask build issues".to_string());
    }

    if input.generated_signet_funding_address {
        passed.push("Real signet/testnet funding address generated by embedded LDK node".to_string());
    } else {
        blockers.push("v0.20 target: generate and display a real signet/testnet funding address".to_string());
    }

    if input.mainnet_lightning_requested {
        blockers.push("Mainnet embedded Lightning is intentionally blocked until restore, liquidity, and receive tests pass".to_string());
    } else {
        passed.push("Mainnet embedded Lightning was not requested".to_string());
    }

    let ready_for_next_ldk_step = input.rust_installed
        && input.frontend_build_passed
        && input.default_cargo_check_passed
        && input.feature_cargo_check_passed
        && input.clean_clone_tested
        && !input.mainnet_lightning_requested;

    LocalValidationPlan {
        ready_for_next_ldk_step,
        safe_for_real_mainnet: false,
        passed,
        blockers,
        local_commands: vec![
            "npm install".to_string(),
            "npm run check:frontend".to_string(),
            "npm run check:tauri".to_string(),
            "npm run check:tauri:ldk".to_string(),
            "npm run validate:local".to_string(),
        ],
        next_code_targets: vec![
            "Fix any Cargo errors in wallet.rs/storage.rs/ocean.rs after local cargo check".to_string(),
            "Fix any ldk-node API mismatches exposed by the feature build".to_string(),
            "Add a feature-gated command that starts/stops an LDK signet node".to_string(),
            "Return a real signet/testnet on-chain funding address from the embedded node".to_string(),
            "Only after funding-address flow works, attempt a real signet BOLT12 offer".to_string(),
        ],
        warning: if ready_for_next_ldk_step {
            "Local validation gates are marked as passed. Move to v0.20 real signet funding-address command. Mainnet remains locked.".to_string()
        } else {
            "Do not move to mainnet or call this product finished. Resolve blockers first, then continue with signet/testnet only.".to_string()
        },
    }
}
