use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LdkSignetBranchStatus {
    pub version: String,
    pub branch_name: String,
    pub cargo_feature: String,
    pub optional_dependency: String,
    pub dependency_wired_in_cargo: bool,
    pub default_build_uses_ldk: bool,
    pub compiled_with_feature: bool,
    pub implemented_now: Vec<String>,
    pub next_local_steps: Vec<String>,
    pub mainnet_guardrails: Vec<String>,
    pub warning: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LdkSignetRuntimeStartInput {
    pub alias: String,
    pub network: String,
    pub data_dir: String,
    pub esplora_url: String,
    pub rgs_url: String,
    pub confirmed_signet_only: bool,
    pub backup_confirmed: bool,
    pub restore_test_confirmed: bool,
    pub inbound_liquidity_plan_confirmed: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LdkSignetRuntimeStartPlan {
    pub safe_to_attempt_local_feature_build: bool,
    pub network: String,
    pub alias: String,
    pub data_dir: String,
    pub cargo_commands: Vec<String>,
    pub runtime_sequence: Vec<String>,
    pub pseudo_code: Vec<String>,
    pub blockers: Vec<String>,
    pub acceptance_tests: Vec<String>,
    pub warning: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LdkSignetOfferRecipe {
    pub goal: String,
    pub prerequisites: Vec<String>,
    pub ldk_api_targets: Vec<String>,
    pub expected_outputs: Vec<String>,
    pub non_goals: Vec<String>,
    pub warning: String,
}

pub fn branch_status() -> LdkSignetBranchStatus {
    LdkSignetBranchStatus {
        version: "v0.13".to_string(),
        branch_name: "feature/ldk-node-signet-runtime".to_string(),
        cargo_feature: "ldk-node-signet-runtime".to_string(),
        optional_dependency: "ldk-node = 0.7.0".to_string(),
        dependency_wired_in_cargo: true,
        default_build_uses_ldk: false,
        compiled_with_feature: cfg!(feature = "ldk-node-signet-runtime"),
        implemented_now: vec![
            "Cargo feature gate added for optional ldk-node signet runtime work.".to_string(),
            "UI now records the minimum runtime inputs needed to start a signet/testnet Lightning node safely.".to_string(),
            "Backend produces a concrete local feature-branch plan and acceptance criteria.".to_string(),
            "Mainnet embedded Lightning remains locked by default.".to_string(),
        ],
        next_local_steps: vec![
            "Install Rust locally and run `cargo check` on the default build.".to_string(),
            "Create branch `feature/ldk-node-signet-runtime`.".to_string(),
            "Run `cargo check --features ldk-node-signet-runtime` and resolve dependency/API errors.".to_string(),
            "Replace v0.13 planning calls with real ldk_node::Builder startup on signet/testnet only.".to_string(),
            "Generate a real signet/testnet BOLT12 offer and verify it is rejected for OCEAN mainnet until release gates pass.".to_string(),
        ],
        mainnet_guardrails: vec![
            "No mainnet embedded Lightning receiving in the default build.".to_string(),
            "No automatic channel opening with real BTC.".to_string(),
            "No mainnet OCEAN payout offer generated by the experimental adapter.".to_string(),
            "Backups, restore test, channel/liquidity plan, and failure-mode docs are required before mainnet.".to_string(),
        ],
        warning: "v0.13 wires the optional ldk-node dependency boundary and branch workflow, but does not yet run a production Lightning node or generate OCEAN-mainnet offers.".to_string(),
    }
}

pub fn start_plan(input: LdkSignetRuntimeStartInput) -> LdkSignetRuntimeStartPlan {
    let mut blockers = Vec::new();
    let network = input.network.trim().to_lowercase();

    if network == "mainnet" || network == "bitcoin" {
        blockers.push("Mainnet requested. v0.13 only permits signet/testnet planning.".to_string());
    }
    if !input.confirmed_signet_only {
        blockers.push("Confirm that this is signet/testnet only.".to_string());
    }
    if !input.backup_confirmed {
        blockers.push("Confirm that recovery words / node secret backup plan exists.".to_string());
    }
    if !input.restore_test_confirmed {
        blockers.push("Confirm that restore will be tested before any mainnet release.".to_string());
    }
    if !input.inbound_liquidity_plan_confirmed {
        blockers.push("Confirm inbound liquidity/channel plan for receiving OCEAN payouts.".to_string());
    }
    if input.data_dir.trim().is_empty() {
        blockers.push("Set an isolated signet/testnet data directory.".to_string());
    }
    if input.esplora_url.trim().is_empty() {
        blockers.push("Set a signet/testnet Esplora URL or local chain source.".to_string());
    }

    let safe = blockers.is_empty();

    LdkSignetRuntimeStartPlan {
        safe_to_attempt_local_feature_build: safe,
        network: if network.is_empty() { "signet".to_string() } else { network },
        alias: if input.alias.trim().is_empty() { "CarlosK-Signet".to_string() } else { input.alias },
        data_dir: input.data_dir,
        cargo_commands: vec![
            "git checkout -b feature/ldk-node-signet-runtime".to_string(),
            "cd src-tauri".to_string(),
            "cargo check".to_string(),
            "cargo check --features ldk-node-signet-runtime".to_string(),
            "RUST_LOG=info cargo test --features ldk-node-signet-runtime".to_string(),
        ],
        runtime_sequence: vec![
            "Build ldk_node::Builder with signet/testnet network only.".to_string(),
            "Set wallet/node storage path to the isolated CarlosK signet data directory.".to_string(),
            "Configure Esplora chain source and rapid gossip sync source.".to_string(),
            "Start the node and persist runtime status.".to_string(),
            "Create a signet/testnet on-chain funding address.".to_string(),
            "Open or request inbound liquidity on signet/testnet.".to_string(),
            "Generate a test BOLT12 offer for a small receive test.".to_string(),
        ],
        pseudo_code: vec![
            "let mut builder = ldk_node::Builder::new();".to_string(),
            "builder.set_network(Network::Signet);".to_string(),
            "builder.set_storage_dir_path(data_dir);".to_string(),
            "builder.set_chain_source_esplora(esplora_url, None);".to_string(),
            "let node = builder.build()?;".to_string(),
            "node.start()?;".to_string(),
            "let offer = node.bolt12_payment().receive(...)?;".to_string(),
        ],
        blockers,
        acceptance_tests: vec![
            "Default build still compiles without ldk-node.".to_string(),
            "Feature build compiles with ldk-node on developer machine.".to_string(),
            "Signet node starts and stops cleanly.".to_string(),
            "Generated test offer starts with lno1 and is clearly labeled signet/testnet.".to_string(),
            "Mainnet requests are rejected in v0.13 and v0.13 test builds.".to_string(),
        ],
        warning: "This is a signet/testnet branch plan. Do not connect real OCEAN payouts or real BTC until mainnet release gates are explicitly implemented and tested.".to_string(),
    }
}

pub fn offer_recipe() -> LdkSignetOfferRecipe {
    LdkSignetOfferRecipe {
        goal: "Generate the first real in-app BOLT12 offer on signet/testnet using ldk-node, then prove CarlosK Wallet can keep the offer separate from OCEAN mainnet until release gates pass.".to_string(),
        prerequisites: vec![
            "Rust toolchain installed locally.".to_string(),
            "Default Tauri build passes.".to_string(),
            "Feature build with ldk-node compiles.".to_string(),
            "Isolated signet/testnet data directory.".to_string(),
            "Recovery backup and restore test plan.".to_string(),
            "Inbound liquidity plan for Lightning receive tests.".to_string(),
        ],
        ldk_api_targets: vec![
            "ldk_node::Builder for node setup.".to_string(),
            "Node::start / Node::stop for lifecycle.".to_string(),
            "Node::onchain_payment().new_address for signet funding address.".to_string(),
            "Node::bolt12_payment() for future BOLT12 receive offer generation.".to_string(),
            "Node::list_channels and balance APIs for readiness checks.".to_string(),
        ],
        expected_outputs: vec![
            "Signet node runtime status.".to_string(),
            "Signet funding address.".to_string(),
            "Signet/testnet BOLT12 receive offer.".to_string(),
            "Offer acceptance-test report.".to_string(),
            "A hard block preventing use of the test offer for OCEAN mainnet payouts.".to_string(),
        ],
        non_goals: vec![
            "No mainnet Lightning receive wallet yet.".to_string(),
            "No automatic channel funding with real BTC.".to_string(),
            "No custodial server.".to_string(),
            "No seed upload or cloud key storage.".to_string(),
        ],
        warning: "v0.13 is the engineering bridge between safe planning screens and the real LDK Node signet implementation. It intentionally remains conservative.".to_string(),
    }
}
