use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LightningPrototypePlan {
    pub version: String,
    pub network: String,
    pub mode: String,
    pub data_dir_hint: String,
    pub can_hold_mainnet_funds: bool,
    pub implemented_now: Vec<String>,
    pub disabled_until: Vec<String>,
    pub developer_next_steps: Vec<String>,
    pub warning: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LightningReceiveReadiness {
    pub ready_for_ocean_mainnet: bool,
    pub checks: Vec<String>,
    pub missing: Vec<String>,
    pub recommendation: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignetNodeConfig {
    pub network: String,
    pub alias: String,
    pub data_dir: String,
    pub esplora_url: String,
    pub listening_enabled: bool,
    pub mainnet_disabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignetNodeStatus {
    pub phase: String,
    pub network: String,
    pub alias: String,
    pub data_dir: String,
    pub offer_generation_available: bool,
    pub simulated_offer: String,
    pub implemented_now: Vec<String>,
    pub blocked_by: Vec<String>,
    pub next_manual_test_steps: Vec<String>,
    pub warning: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LightningSafetyChecklist {
    pub signet_only: bool,
    pub mainnet_locked: bool,
    pub backup_plan_required: bool,
    pub inbound_liquidity_required: bool,
    pub safe_to_receive_mainnet: bool,
    pub checklist: Vec<String>,
}

pub fn prototype_plan() -> LightningPrototypePlan {
    LightningPrototypePlan {
        version: "v0.10".to_string(),
        network: "signet/testnet prototype only, mainnet disabled".to_string(),
        mode: "LDK Node signet prototype checkpoint".to_string(),
        data_dir_hint: "~/.carlosk-wallet/ldk-node-signet".to_string(),
        can_hold_mainnet_funds: false,
        implemented_now: vec![
            "External BOLT12 offer validation".to_string(),
            "OCEAN JSON message inspection".to_string(),
            "BOLT12 pairing check before signing".to_string(),
            "Encrypted mining wallet backup export/restore".to_string(),
            "Signet/testnet Lightning node UX scaffold".to_string(),
            "Safety checklist for future in-app BOLT12 receiving".to_string(),
        ],
        disabled_until: vec![
            "ldk-node dependency is compiled and tested on signet".to_string(),
            "A real signet BOLT12 offer is generated by LDK Node, not by placeholder text".to_string(),
            "Channel backup and restore path is proven".to_string(),
            "Inbound liquidity UX is implemented".to_string(),
            "Force-close/recovery documentation exists".to_string(),
        ],
        developer_next_steps: vec![
            "Create a separate ldk-node-experimental branch".to_string(),
            "Add ldk-node as an optional dependency pinned to a known version".to_string(),
            "Initialize LDK Node on signet only and persist node data in the app data directory".to_string(),
            "Generate and display a real signet BOLT12 offer".to_string(),
            "Write backup/restore tests before enabling mainnet Lightning receiving".to_string(),
        ],
        warning: "v0.10 still does not create a production Lightning wallet. It adds the signet-first developer workflow and UI so contributors can work on LDK safely without risking mainnet funds.".to_string(),
    }
}

pub fn receive_readiness(has_saved_offer: bool, has_backup_confirmed: bool, pairing_matches: bool) -> LightningReceiveReadiness {
    let mut checks = vec![];
    let mut missing = vec![];

    if has_saved_offer { checks.push("BOLT12 offer saved".to_string()); } else { missing.push("Save a BOLT12 offer".to_string()); }
    if has_backup_confirmed { checks.push("Mining wallet backup confirmed".to_string()); } else { missing.push("Confirm mining wallet backup".to_string()); }
    if pairing_matches { checks.push("OCEAN JSON offer matches saved BOLT12 offer".to_string()); } else { missing.push("Verify OCEAN JSON offer matches saved BOLT12 offer".to_string()); }

    let ready = has_saved_offer && has_backup_confirmed && pairing_matches;
    let recommendation = if ready {
        "Ready to sign the OCEAN payout message, assuming the mining address shown is yours.".to_string()
    } else {
        "Do not sign yet. Complete the missing checks first.".to_string()
    };

    LightningReceiveReadiness {
        ready_for_ocean_mainnet: ready,
        checks,
        missing,
        recommendation,
    }
}

pub fn default_signet_config() -> SignetNodeConfig {
    SignetNodeConfig {
        network: "signet".to_string(),
        alias: "CarlosKWalletSignet".to_string(),
        data_dir: "~/.carlosk-wallet/ldk-node-signet".to_string(),
        esplora_url: "https://mutinynet.com/api".to_string(),
        listening_enabled: false,
        mainnet_disabled: true,
    }
}

pub fn start_signet_node_preview(config: SignetNodeConfig) -> SignetNodeStatus {
    let offer_hint = format!(
        "lno1-signet-placeholder-{}-do-not-use-for-ocean-mainnet",
        config.alias.to_lowercase().replace(|c: char| !c.is_ascii_alphanumeric(), "")
    );

    SignetNodeStatus {
        phase: "v0.10 signet LDK Node preview".to_string(),
        network: config.network,
        alias: config.alias,
        data_dir: config.data_dir,
        offer_generation_available: false,
        simulated_offer: offer_hint,
        implemented_now: vec![
            "Lightning node configuration model".to_string(),
            "Signet-only startup preview command".to_string(),
            "Mainnet receiving lockout in UI and backend status".to_string(),
            "Placeholder offer string clearly marked as non-payment data".to_string(),
        ],
        blocked_by: vec![
            "ldk-node is not linked in the default build yet".to_string(),
            "Real BOLT12 generation must be tested on signet first".to_string(),
            "Channel state backup and recovery are not implemented".to_string(),
            "Inbound liquidity management is not implemented".to_string(),
        ],
        next_manual_test_steps: vec![
            "Create an ldk-node-experimental branch".to_string(),
            "Pin ldk-node and related Lightning crates".to_string(),
            "Replace this preview with real NodeBuilder initialization on signet".to_string(),
            "Generate a real signet BOLT12 offer and verify it parses".to_string(),
            "Only after recovery tests pass, design the mainnet migration switch".to_string(),
        ],
        warning: "This is not a real Lightning node yet and the simulated offer must not be pasted into OCEAN. v0.10 is a safe developer checkpoint for signet/testnet integration.".to_string(),
    }
}

pub fn safety_checklist() -> LightningSafetyChecklist {
    LightningSafetyChecklist {
        signet_only: true,
        mainnet_locked: true,
        backup_plan_required: true,
        inbound_liquidity_required: true,
        safe_to_receive_mainnet: false,
        checklist: vec![
            "Never enable mainnet Lightning receive until channel backup/restore is proven".to_string(),
            "Run the first embedded node on signet/testnet only".to_string(),
            "Keep the mining identity wallet separate from main wallets".to_string(),
            "Display liquidity requirements before generating an OCEAN payout offer".to_string(),
            "Make users confirm backup before any receiving feature is enabled".to_string(),
        ],
    }
}
