use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LdkNodeExperimentalStatus {
    pub version: String,
    pub feature_flag: String,
    pub compiled_in: bool,
    pub network: String,
    pub status: String,
    pub implemented_now: Vec<String>,
    pub not_implemented_yet: Vec<String>,
    pub safe_next_steps: Vec<String>,
    pub warning: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignetBolt12OfferRequest {
    pub alias: String,
    pub receiving_label: String,
    pub data_dir: String,
    pub esplora_url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignetBolt12OfferPreview {
    pub network: String,
    pub receiving_label: String,
    pub offer_available: bool,
    pub offer: String,
    pub instructions: Vec<String>,
    pub blocked_by: Vec<String>,
    pub warning: String,
}

pub fn status() -> LdkNodeExperimentalStatus {
    LdkNodeExperimentalStatus {
        version: "v0.10".to_string(),
        feature_flag: "ldk-node-experimental".to_string(),
        compiled_in: cfg!(feature = "ldk-node-experimental"),
        network: "signet/testnet first, mainnet locked".to_string(),
        status: if cfg!(feature = "ldk-node-experimental") {
            "Experimental feature flag is enabled, but the default adapter still blocks mainnet receiving until recovery tests exist.".to_string()
        } else {
            "Default build uses a safe adapter stub. No embedded Lightning wallet is active yet.".to_string()
        },
        implemented_now: vec![
            "Feature-gated Lightning adapter boundary".to_string(),
            "Signet BOLT12 offer request/preview model".to_string(),
            "UI flow that separates placeholder/dev offers from real OCEAN mainnet offers".to_string(),
            "Developer checklist for linking ldk-node later without exposing mainnet funds".to_string(),
        ],
        not_implemented_yet: vec![
            "Real ldk-node dependency is not linked in the default build".to_string(),
            "No real BOLT12 offer is generated by this default build".to_string(),
            "No channel opening, inbound liquidity, or route handling yet".to_string(),
            "No channel backup/restore or force-close recovery yet".to_string(),
            "No mainnet Lightning receiving yet".to_string(),
        ],
        safe_next_steps: vec![
            "Create a separate experimental branch before adding ldk-node".to_string(),
            "Pin ldk-node and Bitcoin/Lightning dependencies to exact versions".to_string(),
            "Initialize node data under an app-specific signet directory".to_string(),
            "Generate a real signet BOLT12 offer and verify it parses".to_string(),
            "Document backup, restore, channel close, and liquidity flows before mainnet".to_string(),
        ],
        warning: "v0.10 does not fake a production BOLT12 wallet. It adds the signet funding/release planning needed before linking real ldk-node on the experimental branch.".to_string(),
    }
}

pub fn preview_signet_offer(request: SignetBolt12OfferRequest) -> SignetBolt12OfferPreview {
    let clean_label = request
        .receiving_label
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
        .collect::<String>();
    let label = if clean_label.is_empty() { "OceanMiningPayout".to_string() } else { clean_label };

    let offer = format!(
        "lno1-signet-adapter-preview-{}-{}-not-real",
        request.alias.to_lowercase().replace(|c: char| !c.is_ascii_alphanumeric(), ""),
        label.to_lowercase()
    );

    SignetBolt12OfferPreview {
        network: "signet".to_string(),
        receiving_label: label,
        offer_available: false,
        offer,
        instructions: vec![
            "This screen is the v0.10 adapter test path, not a real OCEAN payout offer yet.".to_string(),
            "Use it to verify the UI flow for future in-app BOLT12 generation.".to_string(),
            "Do not paste this preview offer into OCEAN mainnet.".to_string(),
            "When ldk-node is wired in, this command will return a real signet BOLT12 offer first.".to_string(),
        ],
        blocked_by: vec![
            "ldk-node not linked in the default build".to_string(),
            "signet channel funding and inbound liquidity not implemented".to_string(),
            "backup/restore tests not implemented".to_string(),
            "mainnet safety gate still locked".to_string(),
        ],
        warning: format!(
            "No real BOLT12 offer was created. Alias '{}', data dir '{}', Esplora '{}' are recorded only for the future ldk-node adapter.",
            request.alias, request.data_dir, request.esplora_url
        ),
    }
}
