use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignetRuntimeFixtureInput {
    pub default_cargo_check_passed: bool,
    pub ldk_feature_cargo_check_passed: bool,
    pub clean_clone_tested: bool,
    pub ldk_dependency_resolved: bool,
    pub generated_real_signet_funding_address: bool,
    pub funded_signet_address: bool,
    pub opened_or_planned_inbound_channel: bool,
    pub generated_real_signet_bolt12_offer: bool,
    pub received_signet_lightning_payment: bool,
    pub restored_node_from_backup: bool,
    pub mainnet_requested: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignetRuntimeFixtureReport {
    pub version: String,
    pub fixture_name: String,
    pub can_advance_to_real_ldk_runtime: bool,
    pub can_generate_real_signet_offer_next: bool,
    pub can_unlock_mainnet_embedded_lightning: bool,
    pub passed: Vec<String>,
    pub blockers: Vec<String>,
    pub fixture_steps: Vec<String>,
    pub local_commands: Vec<String>,
    pub evidence_to_capture: Vec<String>,
    pub warnings: Vec<String>,
    pub next_version_goal: String,
}

fn push_check(passed: &mut Vec<String>, blockers: &mut Vec<String>, ok: bool, pass: &str, block: &str) {
    if ok {
        passed.push(pass.to_string());
    } else {
        blockers.push(block.to_string());
    }
}

pub fn build_signet_runtime_fixture_report(input: SignetRuntimeFixtureInput) -> SignetRuntimeFixtureReport {
    let mut passed = vec![];
    let mut blockers = vec![];

    push_check(
        &mut passed,
        &mut blockers,
        input.default_cargo_check_passed,
        "Default Tauri/Rust backend cargo check passed.",
        "Run and pass: cd src-tauri && cargo check.",
    );
    push_check(
        &mut passed,
        &mut blockers,
        input.ldk_feature_cargo_check_passed,
        "LDK feature cargo check passed.",
        "Run and pass: cd src-tauri && cargo check --features ldk-node-signet-runtime.",
    );
    push_check(
        &mut passed,
        &mut blockers,
        input.clean_clone_tested,
        "Clean clone/unzip validation passed.",
        "Validate the ZIP/repo from a clean folder before trusting local state.",
    );
    push_check(
        &mut passed,
        &mut blockers,
        input.ldk_dependency_resolved,
        "ldk-node dependency resolved locally under the signet runtime feature.",
        "Resolve ldk-node API/dependency errors before adding real runtime calls.",
    );
    push_check(
        &mut passed,
        &mut blockers,
        input.generated_real_signet_funding_address,
        "A real signet/testnet funding address was generated by the embedded node path.",
        "Do not fake funding addresses; the embedded LDK node path must return a real signet/testnet address.",
    );
    push_check(
        &mut passed,
        &mut blockers,
        input.funded_signet_address,
        "The signet/testnet funding address received test coins.",
        "Fund the generated signet/testnet address with faucet coins and confirm the app can detect the balance.",
    );
    push_check(
        &mut passed,
        &mut blockers,
        input.opened_or_planned_inbound_channel,
        "Inbound liquidity/channel plan exists for receiving test Lightning payments.",
        "Receiving over Lightning requires inbound liquidity; define the test channel/LSP plan.",
    );
    push_check(
        &mut passed,
        &mut blockers,
        input.generated_real_signet_bolt12_offer,
        "A real signet/testnet BOLT12 offer was generated by the embedded node path.",
        "Generate a real BOLT12 offer on signet/testnet before any mainnet work.",
    );
    push_check(
        &mut passed,
        &mut blockers,
        input.received_signet_lightning_payment,
        "A signet/testnet Lightning payment was received through the generated offer.",
        "Complete a real signet/testnet receive test before calling embedded Lightning usable.",
    );
    push_check(
        &mut passed,
        &mut blockers,
        input.restored_node_from_backup,
        "The embedded Lightning node was restored from backup and still recovered expected state.",
        "Prove backup/restore before mainnet because Lightning state loss can lose funds.",
    );

    if input.mainnet_requested {
        blockers.push("Mainnet embedded Lightning was requested; v0.26 must block this path.".into());
    } else {
        passed.push("Mainnet embedded Lightning remained blocked.".into());
    }

    let can_advance_to_real_ldk_runtime = input.default_cargo_check_passed
        && input.ldk_feature_cargo_check_passed
        && input.clean_clone_tested
        && input.ldk_dependency_resolved
        && !input.mainnet_requested;

    let can_generate_real_signet_offer_next = can_advance_to_real_ldk_runtime
        && input.generated_real_signet_funding_address
        && input.funded_signet_address
        && input.opened_or_planned_inbound_channel;

    let can_unlock_mainnet_embedded_lightning = can_generate_real_signet_offer_next
        && input.generated_real_signet_bolt12_offer
        && input.received_signet_lightning_payment
        && input.restored_node_from_backup
        && false;

    let mut warnings = vec![
        "v0.26 is a signet/testnet acceptance fixture, not a mainnet Lightning wallet release.".into(),
        "Mainnet embedded Lightning stays locked even if every box is checked; v1.0 requires repeated signet/testnet recovery tests and review.".into(),
    ];
    if input.generated_real_signet_funding_address && !input.funded_signet_address {
        warnings.push("A funding address without test coins is not enough to validate receiving.".into());
    }
    if input.generated_real_signet_bolt12_offer && !input.received_signet_lightning_payment {
        warnings.push("A generated offer is not proof of a working wallet until a test payment is received and recovered after restart.".into());
    }

    SignetRuntimeFixtureReport {
        version: "0.26.0".into(),
        fixture_name: "LDK signet/testnet runtime acceptance fixture".into(),
        can_advance_to_real_ldk_runtime,
        can_generate_real_signet_offer_next,
        can_unlock_mainnet_embedded_lightning,
        passed,
        blockers,
        fixture_steps: vec![
            "Run default cargo check from a clean clone.".into(),
            "Run cargo check with --features ldk-node-signet-runtime.".into(),
            "Start the embedded signet/testnet node path locally.".into(),
            "Generate a real signet/testnet funding address from the node.".into(),
            "Fund the address with signet/testnet coins.".into(),
            "Open or arrange inbound liquidity for test Lightning receiving.".into(),
            "Generate a real BOLT12 offer from the embedded node.".into(),
            "Receive a signet/testnet Lightning payment to that offer.".into(),
            "Restart the app and prove the node still sees the expected state.".into(),
            "Restore from backup in a clean directory and prove funds/state are recoverable.".into(),
        ],
        local_commands: vec![
            "npm install".into(),
            "npm run check:frontend".into(),
            "npm run check:tauri".into(),
            "npm run check:tauri:ldk".into(),
            "npm run diagnose:rust".into(),
        ],
        evidence_to_capture: vec![
            "cargo check output for default backend.".into(),
            "cargo check output for ldk-node-signet-runtime feature.".into(),
            "Generated signet/testnet funding address from the app, redacted if posting publicly.".into(),
            "Signet/testnet funding transaction id.".into(),
            "Generated BOLT12 offer prefix only, never secrets.".into(),
            "Successful signet/testnet payment receive evidence.".into(),
            "Restart/restore test result.".into(),
        ],
        next_version_goal: if can_generate_real_signet_offer_next {
            "v0.27 should replace preview-only BOLT12 logic with a real signet/testnet BOLT12 offer call.".into()
        } else if can_advance_to_real_ldk_runtime {
            "v0.27 should return the first real signet/testnet funding address from the embedded node.".into()
        } else {
            "v0.27 should focus on local Cargo/LDK compile failures before adding more runtime code.".into()
        },
        warnings,
    }
}
